services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Oracle\Typo3Dam\:
    resource: '../Classes/*'
    exclude: '../Classes/Api/*'

  Oracle\Typo3Dam\Controller\SelectorController:
    public: true

  Oracle\Typo3Dam\Service\AssetService:
    public: true

  Oracle\Typo3Dam\Command\DownloadAssetCommand:
    tags:
      - name: 'console.command'
        command: 'oracledam:download'
        description: 'Download asset(s) from Oracle DAM.'
